name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      Browser:
        description: 'Browser'
        default: 'Chrome'
        required: true
      Environnement:
        description: 'Environnement'
        default: 'Preprod'
        required: true
      PublishReport:
        description: 'PublishReport'
        default: true
        required: true
jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: ismailktamirobot/rbfdemocuisine:v1
      volumes:
        - my_docker_volume:/volume_mount
      steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: robot .