name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      Browser:
        description: 'Browser'
        default: 'Chrome'
        required: true
      Environnement:
        description: 'Environnement'
        default: 'Preprod'
        required: true
      PublishReport:
        description: 'PublishReport'
        default: true
        required: true
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Image 
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 

    - run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get -y update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -yqq unzip
        wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
        unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
        chmod 777 /usr/local/bin/chromedriver
        pip install --upgrade pip

    - name: Install requierement 
      run: pip install -r requirements.txt  

    - name: Execute tests
      run:  robot -d reports tests.robot
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: ${{ github.workspace }}/reports